version: "3.3"
services:
  config:
    image: "msansone/config-service:v1"
    ports:
      - "8888:8888"
    environment:
      EUREKA_SERVER: sec.msansone.com.br   
      
networks:
  default:
    # Use a custom driver
    driver: bridge
