spring:
  application:
    name: zuul-service
    
server:
  port: 8070

  
zuul:
  routes:
    stock-db-service:
      path: /api/stockdb/**
      strip-prefix: false
    stock-web-service:
      path: /api/stockweb/**
      strip-prefix: false
    portfolio-service:
      path: /api/portifolio/**
      strip-prefix: false



ribbon:
  ReadTimeout: 1000
  connection-timeout: 1000
  eureka:
    enabled: true
