server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER}:8761/eureka/

#      defaultZone: http://sec.msansone.com.br:8761/eureka/

spring:
  profiles:
    active: native
  application:
    name: config-service 
  cloud:
    config:
      server:
        native:
          search-locations: /Users/msansone/Documents/gitBackup/spring-cloud-mystocks/config-service/src/main/resources/configs/
