server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-service 
  cloud:
    config:
      server:
        native:
          search-locations: /Users/msansone/Documents/gitBackup/spring-cloud-mystocks/config-service/src/main/resources/configs/
