server:
  port: 8085


feign:
  client:
    config:
      stock-web-service:
        connectTimeout: 600000
        readTimeout: 600000

        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    